version: "3"
services:
  frontend:
    build: ./client
    expose:
      - 1234
    ports:
      - 1234:1234
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    links:
      - backend
    command: npm run start
  backend:
    build: ./server
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/usr/src/app/src
    command: npm run dev
