version: "3"
services:
  frontend:
    container_name: phones_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myproject/phones_client
    ports:
      - "1234:1234"
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: phones_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: myproject/phones_server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
